# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.13.0 on Tue May  7 13:40:00 2024
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': 'C:\\Users\\ryanm\\Dropbox '
                              '(Personal)\\Files\\apec_8601\\env8601_project\\base_data\\invest\\esa_and_modis_biophysical_table.csv',
    'dem_path': 'C:\\Users\\ryanm\\Dropbox '
                '(Personal)\\Files\\apec_8601\\env8601_project\\base_data\\invest\\dem.tif',
    'drainage_path': '',
    'erodibility_path': 'C:\\Users\\ryanm\\Dropbox '
                        '(Personal)\\Files\\apec_8601\\env8601_project\\base_data\\invest\\soil_erodibilty.tif',
    'erosivity_path': 'C:\\Users\\ryanm\\Dropbox '
                      '(Personal)\\Files\\apec_8601\\env8601_project\\base_data\\invest\\erosivity.tif',
    'ic_0_param': '.5',
    'k_param': '2',
    'l_max': '1.22',
    'lulc_path': 'C:\\Users\\ryanm\\Dropbox '
                 '(Personal)\\Files\\apec_8601\\env8601_project\\seals\\projects\\BLZ_standard\\intermediate\\stitched_lulc_simplified_scenarios\\lulc_esa_seals7_ssp5_rcp85_luh2-message_bau_2045_clipped.tif',
    'n_workers': '-1',
    'results_suffix': '',
    'sdr_max': '0.8',
    'threshold_flow_accumulation': '1000',
    'watersheds_path': 'C:\\Users\\ryanm\\Dropbox '
                       '(Personal)\\Files\\apec_8601\\env8601_project\\base_data\\invest\\watershed.shp',
    'workspace_dir': 'C:\\Users\\ryanm\\Desktop\\sediment-ssp5-2045',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
